name: absensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  scroll_to_index: ^3.0.1
  intl: ^0.19.0
  google_maps_flutter: ^2.9.0
  location: ^6.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  geocoding: ^3.0.0
  cloud_firestore: ^4.14.0
  firebase_database: ^10.4.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  firebase_storage: ^11.6.0
  http: ^1.2.2
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_logo.png"
